

// auth server request
POST http://localhost:3000/api/register
Content-Type: application/json

{
    "username":"guy",
    "password":"guy",
    "email":"guyhazut2000d@gmail.com"
}

###
// auth server request
POST http://localhost:3000/api/login
Content-Type: application/json

{
    "username":"guy",
    "password":"guy",
    "email":"guyhazut2000@gmail.com"
}

###


GET http://localhost:3000/api/login
Content-Type: application/json


###
